### ISSUE TITLE
change in model size

### ISSUE THREAD

**Issue by hosh0425** [mikaelarguedas/gazebo_models#2] opened 2017-03-26 20:48 UTC
I made my markers model and every thing is fine but when I save the world and reopen this the marker size always change to 500*500mm.even I changed the default size in  program to 200mm , every time I add this marker,it's size is 200*200 but after save and exit and reopen it is 500*500.the directory marker0 which we should copy to .gazebo/models , it's model size always is 500*500 and I think if I could change this size the problem will be solve , but I don't know how I should change the marker0 model size.
my gazebo is version 7.5 in ros kinetic

**Comment by hosh0425** [comment] 2017-03-26 21:25
in /ar_tags/model/marker0/meshes in Marker0.dae  in line 
<float_array id="Cube-mesh-positions-array" count="24">
I divided all of the numbers by two and now  each model size will change to 250*250 after save and reopen . my problem solved and you based on your desire size could divide this numbers :)

**Comment by mikaelarguedas** [comment] 2017-03-27 00:02
Hi @hosh0425,
Thanks for reporting the save/reopen world issue not conserving the size. Glad you found a way to make it for your use case.

Looking at it a bit more closely, it looks like a bug in gazebo "save world" function. The markers generated by this script have a constant "size" (500x500), and they are scaled according to the `--size` argument you pass to the script. They display properly in gazebo with the right scale but when they are saved, gazebo doesn't save the scale attribute so they show up with the original size (500x500) when you reopen the world.

I think the scaling approach is more convenient because you don't have to modify the mesh (.dae) itself but only how gazebo display them. I'll have a look at gazebo/sdformat documentation to know if this is the expected behavior. If it's a bug I'll open an issue upstream, if not I'll modify this script to change the size rather than the scale.

**Comment by mikaelarguedas** [comment] 2017-03-27 00:54
Found [this issue](https://bitbucket.org/osrf/gazebo/issues/2208/save-world-saves-incorrect-mesh-scale) on gazebo that indicates it's a bug that will be fixed upstream.
To make you modifications easier in the meantime you can modify your world file rather than your meshes (.dae files). To do so, replace ```<scale>1 1 1</scale>``` (1000x1000) by the scale you want: ```<scale>0.25 0.25 0.25</scale>``` if you want 250x250mm markers.

Hope this helps

**Comment by mikaelarguedas** [comment] 2020-01-13 16:22
This is still an issue in Gazebo7, but works fine on Gazebo9.

I'll close this as wontfix as the bug lies in Gazebo itself 

Thanks again @hosh0425 for reporting

**Closed as completed by mikaelarguedas** 2020-01-13 16:22 UTC
Labels: wontfix
